export { default as Login } from "./Login"
export { default as Register } from "./Register"
export { default as Profile } from "./Profile"
export { default as Dashboard } from "./Dashboard"
export { default as CreateFood } from "./CreateFood"
export { default as Search } from "./Search"
export { default as Home } from "./Home"
export { default as ProfileSetup } from "./ProfileSetup"