POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "john",
    "email": "john@doe.com",
    "password": "John123"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "john",
    "password": "John123"
}

###
POST http://localhost:3000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Njc2ODA0MWY4MzI5NzY1ZWVmNzMwNiIsImlhdCI6MTY4NDUwNjMxNSwiZXhwIjoxNjg0NTA3MjE1fQ.TQEor-e1N5oOsl2O-gjGcw6eSa4rJqkKNvGVx615RV4

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Njc2ODA0MWY4MzI5NzY1ZWVmNzMwNiIsImlhdCI6MTY4NDUwNDY2MCwiZXhwIjoxNjg0NTA1NTYwfQ.nBptmfNkpYV8A4iYljTZbgLnXdOgYfD_FIhJJglUMuw"
}